### ISSUE TITLE
bug: an "indefinite" impactTimeEnd displays as 1969-12-32 in the metadata

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#379]
### To Reproduce

Look at the [metadata of any hypercert](https://ipfs.io/ipfs/bafybeifzpeq22jjdiyzrt7zgtqtbkqsqx4tiozlz7ga2gacj7phl7csxdu)

<img width="859" alt="image" src="https://user-images.githubusercontent.com/42869436/221037356-1afb71ae-ae0b-4fef-80a8-7a6ca0c787f8.png">

### Describe the Bug

an "indefinite" impactTimeEnd displays as `1969-12-32` in the metadata

### Expected Behavior

according to [this](https://github.com/hypercerts-org/hypercerts/blob/279e58bfeae5798049819ab7568eb282d4855a3e/frontend/components/forms.tsx#L208), a date of zero should display as "indefinite"

**Comment by ryscheng** [comment]
Nice find! Fun fact, the number represents [UNIX time](https://en.wikipedia.org/wiki/Unix_time) so the number represents how many seconds have elapsed since Jan 1, 1970. In other words, 0 is 0 seconds from 1/1/1970, or I guess in this case it thinks it's 12/32/1969. That seems like it might even be a bug in the Javascript engine. 

Either way generally, this why we have to be super careful anytime we have a special value. It's easy to forget everywhere we need to check for it. (Better to avoid special values if you can).

In this case, what do we want to display? `2022-09-22 -> indefinite`?

**Comment by ryscheng** [comment]
Fixed here
https://github.com/hypercerts-org/hypercerts/pull/383/files
