### ISSUE TITLE
feat: the projects in the pilot keep fractions that they can sell later

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#438]
To test the marketplace idea, it would be great if we can expand the scope of the pilot. Let's discuss in the sprint planning if that is feasible.

**Comment by ccerv1** [comment]
We'll need to determine which of the options (discussed on yesterday's standup) we want to pursue for now. I'd recommend proposing something specific and then closing out this issue.

**Comment by holkeb** [comment]
As posted on Discord:

Simplest solution is that the minter keeps 50% of the units, i.e. the units from the current allowlist are doubled and the second half assigned to the minter.

If it is technically OK to implement a choice for the projects, we can also implement my older suggestion that the projects can choose to keep 25%, 50% or 75%. To test the main hypotheses this isn't necessary though. If it is easy from an engineering perspective, then I'm happy about such a solution as well.

**Comment by ccerv1** [comment]
Per Slack conversation:
---
Here are some options:
1. As per discussion earlier this week, modify the dApp so the minter automatically gets a % or # of tokens added to the allowlist. 
@ryscheng  would need to implement this since it requires modifying the allowlist used to create the merkle tree.

2. I could arbitrarily add a % or # of tokens to the allowlist for the project creators (eg, 1000 tokens for projects with an EOA wallets, and 1000 tokens per signer for projects with a multisig).

3. We leave as is. If a creator donated to their own project, then they can sell those hypercerts. Or, they can follow the minting guide to modify the allowlist.

Response from @holkeb:

I'm ok with implementing it such that the minter automatically keeps 50% of the tokens, ie option 1.

In the code I believe it makes sense to have the 50% as a variable that we might want to let the user set in the front-end in the future, but for now keep it at 50% for all projects to reduce the choices.

**Comment by ccerv1** [comment]
@ryscheng another thing to be mindful of is that we'll probably need the function to check if the minter is already on the allowlist and, if so, add the new fractions to their current total rather than create a new entry

**Comment by ryscheng** [comment]
So this PR refactors the allowlist processing code
https://github.com/hypercerts-org/hypercerts/pull/466

It's hardcoded to keep 50% of the hypercert to the minter.  We'll need to update the Plasmic project to make it clear to the user that's what we're doing
CC @ccerv1 

CC @holkeb Let's file a new issue once we have a clear idea of what UX we want to expose to the user (i.e. should we let the user enable / disable this? Should the user choose what percentage and how?)

**Comment by holkeb** [comment]
great, I'll update the create form with a note about this

**Comment by holkeb** [comment]
Added the note in plasmic: "50% of the hypercert will be distributed according to this allowlist; the other 50% will be owned by you, i.e. the creator of the hypercert, and can be transferred later."

We can allow projects to choose this percentage later (new issue, closing this for now)
