### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#50]

**Comment by ryscheng** [comment]
Feedback received so far:

1. In HypercertMinter I see you have a constructor and it’s also a implementation for a proxy so probably if the plan is to use this only as a implementation the constructor can be removed which would reduce the coodesize 

2. Also in HypercertMinter, SemiFungible1155 the arrays part of the signatures being read on are defined as memory, good to use calldata instead would be   cheaper

3. the for loop increments & some other arithmetic calculations (optional depending on the logic) can be wrapped in side unchecked block which would again be cheaper

4. I noticed here https://github.com/Network-Goods/hypercerts-protocol/blob/dev/src/SemiFungible1155.sol#L198 the for loop is starting with index as 1 is this intentional ? Since at other places it is 0 indexed

5 I like the masking ops in the contract, only thing is if only few bits in uint256 are used that is not going to make the tx's cheap since evm will pad the other bits etc just a small observation

**Comment by ryscheng** [comment]
Crosslinking a potential issue
https://github.com/Network-Goods/hypercerts-protocol/issues/80

**Comment by bitbeckers** [comment]
Cool, great to get some feedback after all the changes we've made!

1.    _In HypercertMinter I see you have a constructor and it’s also a implementation for a proxy so probably if the plan is to use this only as a implementation the constructor can be removed which would reduce the coodesize_

Yes, this is compliant with OpenZeppelin docs and guidelines: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol

Is this something we should change? I'd like to learn more in that case.

2.    _Also in HypercertMinter, SemiFungible1155 the arrays part of the signatures being read on are defined as memory, good to use calldata instead would be cheaper_

Good find. For some this is because we inherit OZ contract and they use `memory`. Going from `calldata` to `memory` would be more costly I believe, but it's something we can tweak.

@ryscheng this is something that can break UUPS upgrades because the signatures changes so we should postpone this to long

 3.   the for loop increments & some other arithmetic calculations (optional depending on the logic) can be wrapped in side unchecked block which would again be cheaper

Agreed, but also a very minimal optimisation on the scale of the gas cost. Valuable none-the-less so I'd propose putting these optimisations on the backlog but not a must have for the upcoming milestone @ryscheng 

4.    I noticed here https://github.com/Network-Goods/hypercerts-protocol/blob/dev/src/SemiFungible1155.sol#L198 the for loop is starting with index as 1 is this intentional ? Since at other places it is 0 indexed

Oh good spot! I think it's an artifact from some PoC itterations. We can just as simple do ++ on line 193. I'll put it in a 'Tweaks and cleanup' issue

 5.   I like the masking ops in the contract, only thing is if only few bits in uint256 are used that is not going to make the tx's cheap since evm will pad the other bits etc just a small observation

Yes, 100. @ryscheng I've seen talks on the amount of mintable units. Somebody suggested beeping it <4bits, or at least a range regular applications also handle well. We've left the split for claim | fractions at 128 | 128 bits but we could shift this of course.

**Comment by bitbeckers** [comment]
Static code analysis using https://github.com/Picodes/4naly3er/
[report.md](https://github.com/Network-Goods/hypercerts/files/10522165/report.md)

**Comment by ryscheng** [comment]
[Hypercerts-security-review.md](https://github.com/Network-Goods/hypercerts/files/10693287/Hypercerts-security-review.md)

**Comment by ryscheng** [comment]
Fixes here
https://github.com/hypercerts-org/hypercerts/pull/266

Going to close this out until we decide to do another audit
