### ISSUE TITLE
Decide on evaluation schema

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#508]
### Describe the feature you'd like to request

Regardless of whatever evaluation mechanism we end up using
https://github.com/hypercerts-org/hypercerts/issues/439
we'll need to agree on a schema for storing metadata.

### Describe the solution you'd like

Let's use this issue to come to agreement

### Describe alternatives you've considered

N/A

**Comment by bitbeckers** [comment]
My proposal would be to build an aggregation layer that enables pointing to multiple services. Similar to how Allo manages Grants Rounds, Applications and Participants, we'd build a web of pointers that we need to be able to index client-side (using the SDK).

Evaluation contract:
- Knows pointer to evaluations for Hypercerts (mapping contractAddress => Hypercert => Pointer)
- Pointer points to Evaluation on IPFS similar to the current metadata
- EvaluationPointer could in the data either point to EAS or another service/source

Indexing:
- Graph or other indexing service for reading the data in the pointer (non-sense pointer are filtered out because we can't read them)
- Maintain an Evaluations state relating all evaluations (and the sentiment?) to a hypercert

Client side:
- Read: Use the Indexing service
- Create: UX for different types of evaluations, with the MVP being EAS

Schema:
EAS
```json
{
hypercert: {
    chainID: 10, 
    contract: 0x00...0000, 
    claimID: 1},
evaluation:{
    type: "EAS",
    chainID: 1,
    contract: 0x000...0345,
    uid: 1337
}
}
```

IPFS/Other
```json
{
hypercert: {
    chainID: 10, 
    contract: 0x00...0000, 
    claimID: 1},
evaluation:{
    type: "IPFS",
    CID: casxascnuacasdjncme9...dasdnasda
}
}
```

**Comment by ryscheng** [comment]
Yep! This makes sense to me and is pretty much what I was imagining. Thanks for laying out concrete examples to make it more clear.

I'd throw in one more:
```
{
    "hypercertRegion": {
        "impactScope": ..., 
        "workScope": .., 
        "contributors": ...
       ....
    },
    ...
}
```

We can imagine evaluations for regions of the impact space that haven't necessarily been claimed yet. Will be a pain in ass to query for all overlapping regions, but this is a possibility. Probably lower priority to worry about for now.

**Comment by ccerv1** [comment]
I like this basic schema as well. I created a new issue for us to start applying the schema to #574 -- attesting that a hypercert is a duplicate (made by the creator) or a collision (the creator wants to contest the legitimacy of someone else's hypercert that is colliding with their own)

**Comment by bitbeckers** [comment]
Closing this in favor or #574
