### ISSUE TITLE
On-chain claim data and dynamic art

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#510]
### Describe the feature you'd like to request

It'd be nice to give users the option to store claim data on-chain. Once we do that, it should be easier to create dynamic art (e.g. show the percent ownership in the image of the fraction token)

### Describe the solution you'd like

TBD

### Describe alternatives you've considered

Keep things off-chain

**Comment by ryscheng** [comment]
https://metaversal.banklesshq.com/p/dynamic

**Comment by bitbeckers** [comment]
We can use HTML hosted on IPFS with input parameters similar to the implementation here: https://github.com/bitbeckers/cookiejar-contracts/blob/main/src/ERC6551/nft/CookieNFT.sol

(The HTML can be found in the nft dir above the file)

In turn you'll get this path that will be returned when `uri` is called:
https://ipfs.io/ipfs/QmTE41U14KCkjXDYwMb5QzEYkUZivdvo9oBXuKLmUJDddT?seed=42069&balance=1000000000000000000&amount=100000000000000000

This would work with our setup since we are able to handle calls based on a fractionId. We now map the fractionID to a claimID, so we are capable of retrieving the IPFS structure (claimID) to parameters (tokenID). 

The seed could be used to render backgrounds or we can store one per claimID.

**Comment by ryscheng** [comment]
Yep, the contracts make a lot of sense, I think I was more confused about how IPFS treats query strings
We've struggled with that in the past, for example here:
https://github.com/hypercerts-org/hypercerts/issues/480
In this issue, Fleek was mucking with our query strings and redirecting us with different query parameters in an unpredictable way.

Separate question: does OpenSea show HTML if the URI points to HTML?

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/10
