### ISSUE TITLE
feat: back button in view goes to correct tab and scrolling position

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#557]
The back button on the view page doesn't remember which tab the user was on if it goes back to the gallery page (https://testnet.hypercerts.org/app/gallery).

Ideally it would remember the tab as well as where the user left the page, ie the scrolling position

The back button:
![Image](https://user-images.githubusercontent.com/103380539/233718165-e75faa89-a69c-4927-9a0d-0a8f6f9dc4da.png)

The tabs I meant:
![Image](https://user-images.githubusercontent.com/103380539/233718485-3e2b6136-2ee8-468b-bcc7-f1587d0c6e8c.png)

**Comment by ryscheng** [comment]
Notes from our debugging session today:
We aren't storing your current tab or scroll location into history, so it's by design that this currently doesn't work yet.

In the future, we plan to have a more general-purpose filtering mechanism, and it seems like the right point to add the filters into a querystring that we can push into history. For now we'll deprioritize this until we implement filters.

**Comment by bitbeckers** [comment]
Works in current `/app/gallery-all`. 'Back' routes back to the selected collection
