### ISSUE TITLE
feat(dapp): display the work timeframe below the title in a HypercertListItem

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#727]
### What is it?

<img width="572" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/42869436/6897769a-8887-437f-aa77-179a197770cd">

**Comment by ryscheng** [comment]
You'll want to expose slots in the List Item component that accept text.
Then in the Dashboard, pass in the right data to those slots

**Comment by holkeb** [comment]
Done. We already had a subtitle slot :D

@ryscheng a feature that would be neat is if hypercerts that have the same `scope of work` could be clustered. I assume that would be quite some work, right? i.e. we have a repeat element on all unique `scope of work` and then inside that a repeat element on all hypercerts with that `scope of work`. If this would be a small change, I would like to do it, but it doesn't seem trivial, right?

**Comment by holkeb** [comment]
Also added time of work more visibly to the view page

**Comment by holkeb** [comment]
called "done" too early... it doesn't show up on the testnet implementation, even though it is shown in plasmic

plasmic
![Image](https://github.com/hypercerts-org/hypercerts/assets/103380539/1c1509ce-9c0b-43ab-9b9d-4213cd7596ef)

vs. testnet
![Image](https://github.com/hypercerts-org/hypercerts/assets/103380539/33c9f38f-aa37-47e5-8460-454b1538c8a1)

I'll check if I can find the bug here myself, but if you have an idea @ryscheng, let me know

**Comment by holkeb** [comment]
fixed itself somehow :D
