### ISSUE TITLE
integrate treemap from observablehq into plasmic

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#770]
I would like to integrate this treemap on the zuzalu billboard page in plasmic: https://observablehq.com/d/c857fa5c110524ee

Observablehq says ofr Runtime with React:

This code uses the [Runtime API](https://observablehq.com/@observablehq/downloading-and-embedding-notebooks) to generate a React component. From the terminal, run:

> yarn add @observablehq/runtime@5
> yarn add "https://api.observablehq.com/d/c857fa5c110524ee.tgz?v=3"

Then copy and paste the following component into your application:

> import React, {useRef, useEffect} from "react";
> import {Runtime, Inspector} from "@observablehq/runtime";
> import notebook from "c857fa5c110524ee";
> 
> function Notebook() {
>   const chartRef = useRef();
> 
>   useEffect(() => {
>     const runtime = new Runtime();
>     runtime.module(notebook, name => {
>       if (name === "chart") return new Inspector(chartRef.current);
>     });
>     return () => runtime.dispose();
>   }, []);
> 
>   return (
>     <>
>       <div ref={chartRef} />
>       <p>Credit: <a href="https://observablehq.com/d/c857fa5c110524ee">Zuzualu hypercerts by category by hypercerts</a></p>
>     </>
>   );
> }
> 
> export default Notebook;

If you need to make changes, you can fork the treemap on observablehq (or I can add you as a collaborator if you have an account)

Let's integrate it and hide it for now @ryscheng. I will then update the data an publish it.

**Comment by holkeb** [comment]
That looks great, thank you @ravenac95.

When I implement it, it shows an empty child

**Comment by ravenac95** [comment]
Oh interesting. on my phone sorry I think I may have accidentally assigned you. Let me take a look!

**Comment by ravenac95** [comment]
On the dynamic bit. Unfortunately i looked into it. Not possible based on how they integrate

**Comment by holkeb** [comment]
Thanks, and no hurries, absolutely not urgent and can wait

**Comment by ravenac95** [comment]
Oh weird. @holkeb I didn't notice this earlier in my tests because I wasn't paying attention to what the UI was showing on plasmic. I added a place where you could change the text underneath the component but Plasmic Studio decided to render it with that `ZuzaluHypercertTreemap: Slot: Children` label. Oddly,  if you a) add some kind of child to that section underneath the visualization or b) do a preview of a page containing the component you get my intended view of if you choose not to add anything custom below the object. I can change that back to simply include some text. Do you just want the credit like so?:

<img width="883" alt="Screenshot 2023-06-10 at 18 07 07" src="https://github.com/hypercerts-org/hypercerts/assets/862590/50b1ecda-76b4-4ca4-92a6-48e0d6d51163">

**Comment by ryscheng** [comment]
I think reuven did the right thing the first time. Plasmic will show a placeholder if your code component expects a child but you haven't put one in yet. If you want something there, add it. If you don't, I'd add an empty vertical stack to make it explicit. Either one will get rid of the visual placeholder

**Comment by ryscheng** [comment]
@ravenac95 I think you forgot to close this? I see you marked it as done in the project board.

FYI, if you close the issue, it's auto-marked as done in the project board

**Comment by ravenac95** [comment]
Oh it got reopened but ya I think there is a follow on task here to generalize this. I’ll make an issue and close this
