### ISSUE TITLE
story: As an owner of a hypercert, I want to be able to link and update images that are displayed on sponsorship billboards.

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#917]
- [x] https://github.com/hypercerts-org/hypercerts/issues/915
- [ ] #1125
- [ ] #1126
- [ ] #1127
- [ ] #1128
- [ ] #1130
- [ ] #1129
- [ ] #1131
- [ ] #1132
- [ ] #1133

**Comment by bitbeckers** [comment]
@benedictvscriticus food for cleanup

**Comment by benedictvscriticus** [comment]
@holkeb said on Jun 29:

Issue https://github.com/hypercerts-org/hypercerts/issues/915 describes updating the treemap, such that images are displayed.

This issue describes how the billboard can access these images and how hypercert owners can choose the images.

Expected behavior
- Hypercert owner can choose and update which image will be displayed on the sponsorship billboard of a hypercert
- Hypercert owner can choose and update which image will be displayed on a sponsorship billboard of a hypercert if she didn't specify an image for this hypercert specifically (default image of hypercert owner)
- The billboard displays the newest associated image in the space that is allocated to the hypercert owner

Suggested solution
- Create a database with the following columns: wallet address, hypercert identifier, link to image
- Create a form to allow hypercert owners to add an entry to the database linking a new images to their address for specific hypercerts
- Create a form to allow hypercert owners to add an entry to the database linking a new default image to their address with an empty entry for the hypercert identifier
- The billboard looks for the newest image that is associated with the owner address and the hypercert. If no image is linked to the owner address and hypercert, the billboard looks for the default image of the owner address, i.e. the newest image associated with the owner address with an empty entry for the hypercert identifier
- Ideally a hypercert owner can easily upload a new image and doesn't need to do that in a separate step as it is currently done when creating a hypercert

Open questions
- Do we need different image sizes and proportions for different spaces?

**Comment by Jipperism** [comment]
@holkeb @benedictvscriticus is this the implementation we want to go with for now? I think for v1, it might be sufficient to just have a 2 tiered approach? E.g. hyperboard owner can upload default sponsor_metadata per address. Hypercert owners can overwrite this once they've claimed the cert, if they desire to do so.

**Comment by bitbeckers** [comment]
@Jipperism @holkexyz this is currently in hyperboards, correct? If not, feel free to reopen and assign it on the roadmap
