### ISSUE TITLE
TASK: Design Hyperboard minter

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#993]

**Comment by bitbeckers** [comment]
With my current understanding, it's valuable to consider the ERC6551 standard for the hyperboard. A 6551 enables 721 tokens to hold assets like ERC 20, 721 or 1155 tokens. This enables us to mint a hyperboard that holds and controls hypercerts. This also makes these hypercerboard transferable and -in theory- a hyperboard can own a hyperboard (because a 721 holds a 721).

Admin flows of the hyperboard state could be assigned to a DAO, mulitisig or allowlist. Or the allowlist could be managed by a multisig.

I'm just leaving this thought here for future reference. But after FTC I think we should make a PoC out of this with the learnings we gathered up to that point.
